

# This is a basic workflow to help you  get started with Actions
name: Build and Deploy Spring Boot to AWS EC2

on:
  push:
    branches: [ master ]

env:
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  CODE_DEPLOY_APP_NAME: ${{ secrets.CODEDEPLOY_APPLICATION_NAME }}
  DEPLOYMENT_GROUP_NAME: ${{ secrets.CODEDEPLOY_COMPILE_GROUP }}

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

         #      - name: Setup Java JDK 11
      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          #          java-version: 11
          java-version: 11

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database:  ${{ secrets.RDS_DATABASE }}
          mysql user: ${{ secrets.RDS_MYSQL_ID }}
          mysql password: ${{ secrets.RDS_MYSQL_PASSWORD }} # github Secret 탭에서 설정하세요!


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash


      - name: Build with Gradle
        run: ./gradlew build
        shell: bash


      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.MY_KEY }}
          aws-secret-access-key: ${{ secrets.MY_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{secrets.BUCKET_NAME}}/${{secrets.PROJECT_NAME}}/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name  ${{secrets.CODEDEPLOY_APPLICATION_NAME}} --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name ${{secrets.CODEDEPLOY_COMPILE_GROUP }} --s3-location bucket=${{ secrets.BUCKET_NAME}},bundleType=zip,key=${{secrets.PROJECT_NAME}}/$GITHUB_SHA.zip





